channels:
  - plotly
  - pyviz
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7.5
  - cartopy=0.18.0
  - geos=3.8.0
  - geoviews-core=1.6.6
  - holoviews=1.13.5
  - matplotlib=3.3.2
  - netcdf4=1.5.3
  - numpy=1.19.1
  - pandas=1.1.3
  - pillow=7.2.0
  - tabulate
  - pip=20.2.2
  - xarray=0.16.1
  - xrft=0.2.2
  - pip:
    - einops==0.3.0
    - opencv-python-headless
    - scikit-learn
    - ruamel.yaml


